---
#ansible-playbook -i hosts.yml compose2.yml --ask-become-pass --ask-pass --extra-vars='pubkey="<pubkey-for-super-user>”’
#Has a problem where target user must become root\
#https://docs.ansible.com/ansible/latest/modules/list_of_all_modules.html
- name: Prepare for keyspray
  hosts: local
  become: true:
  become_user: e**
  tasks:
  - name: Create ansible dir
    file:
      path: "./ansible"
      state: directory
  - name: Generate sshkey 
    openssh_keypair:
      path: ./ansible/id_rsa
      force: true
- name: Distribute ssh
  hosts: all
  become: true
  become_user: e** 
  tasks:
  - name: Make ssh directory
    file:
      path: "/home/e**/.ssh"
      state: directory
  - name: Create empty file
    file:
      path: "/home/e**/.ssh/authorized_keys"
      state: touch
  - name: Place key
    lineinfile:
      path: "/home/e**/.ssh/authorized_keys"
      line: "{{ pubkey }}"
      vars: #Var order might be wrong 
        pubkey: "{{ lookup('file', './ansible/id_rsa') }}"
- name: Clean install docker
  hosts: all 
  become: true:
  become_user: root #Problem 
  tasks:
    - name: Fix filesystem 
      docker_prune:
        builder_cache: yes
        containers: yes
        images: yes
        volumes: yes
    - name: Remove old docker versions
      yum:
        name: {{ docker_packages }}
        state: absent
      vars: 
        packages:
          list: docker #Uncertain
    - name: Purge /data/docker 
      file:
        state: absent
        path: "/data/docker/"
    - name: Purge /?/docker #?
      file:
        state: absent
        path: "/?/docker/"
    - name: Build /data/docker directory 
      file:
        path: /data/docker 
        state: directory
        mode: '777'
    - name: Build /?/docker directory #?
      file:
        path: /?/docker 
        state: directory
        mode: '777'
    - name: Create symbolic link 
      file: #I read the documentation for src/dest but I don't like it
        src: /data/docker
        dest: /?/docker #?
        state: link
        mode: '777' 
    - name: I forgot what else this needs
    - name: Add docker repo
      yum_repository:
        name: docker_repository
        baseurl: #url
    - name: Install docker #Can't figure out how to disable upgrade
      yum:
        name: ? #Pick verison
      yum:
        name: ? #Pick version 
- name: Clean install helm, kubectl, rke on local 
  hosts: local
  become: true
  become_user: root 
  tasks:
    - name: Build tmp directory 
      file:
        path: ./tmp 
        state: directory
        mode: '777'
    - name: Grab helm 
      get_url:
        url: #
        dest: ./tmp/helm 
        mode: '777'
    - name: Unpack helm
      unarchive:
        src: ./tmp/helm
        dest: ./temp/helm
        mode: '777'
        #May care about remote source
    - name: Grab kubectl
      get_url:
        url: #
        dest: ./tmp/kubectl
        mode: '777'
    - name: Grab rke
      get_url:
        url: #
        dest: ./tmp/rke
        mode: '777'
    - name: Move helm to bin
      copy:
        src: ./tmp/helm
        dest: #bin/helm
        mode: '777'
        remote_src: yes
        force: yes
    - name: Move kubectl to bin
      copy:
        src: ./tmp/kubectl
        dest: #bin/kubectl
        mode: '777'
        remote_src: yes
        force: yes
    - name: Move rke to bin
      copy:
        src: ./tmp/rke
        dest: #bin/rke
        mode: '777'
        remote_src: yes
        force: yes
- name: Clean install helm, kubectl, rke on master 
  hosts: master
  become: true
  become_user: root
  tasks:
    - name: Delete old directories 
      file:
        path: #Targets
        state: absent
    - name: Move helm to bin
      copy:
        src: ./tmp/helm
        dest: #bin/helm
        mode: '777'
        force: yes
    - name: Move kubectl to bin
      copy:
        src: ./tmp/kubectl
        dest: #bin/kubectl
        mode: '777'
        force: yes
    - name: Move rke to bin
      copy:
        src: ./tmp/rke
        dest: #bin/rke
        mode: '777'
        force: yes
- name: Clean tmp files
  hosts: local
  tasks:
    - name: Remove tmp files
      file:
        path: ./tmp
        state: absent
- name: Create cluster #https://docs.ansible.com/ansible/latest/modules/helm_module.html#helm-module
  hosts: local
  tasks:
    - name: Make sure no existing compose
      file: 
        path: ./rancher-compose.yml
        state: absent
    - name: Write the compose file
      file:
        path: ./rancher-compose.yml
        state: present
    - name: fill the compose file
      blockinfile:
        path: ./rancher-compose.yml
        block: | 
          Stuff
          {{ hosts }}
          Stuff
      with_hosts: "{{ groups['master'] }}"
      blockinfile:
        path: ./rancher-compose.yml
        block: | 
          Stuff 
          {{ groups['loadbalancer'] }}
          Stuff
    - name: Create the rancher cluster
      command: 
        free_form: #Rke up 
    - name: Grab tiller #?
    - name: Deploy tiller #?
    - name: Grab certs #?
    - name: Deploy certs #?
    - name: Grab rancher 
    - name: Deploy rancher 
#If being picky could write to add rancher hosts in the script maybe?? I don't actually know       
      