---
-name: Install Rancher server 
    vars_prompt:
        - name: username
          prompt: "What is service username?"
          private: no 
        - name: password
          prompt: "What is service password?"
          private: yes
    become: true
    become_user: {{ username }}
    gather_facts: true
    - name: Enable ssh for target machines
      hosts: local
      tasks:
        - name: Install #sshprogram
          yum: name=? state=present #Forgot
        - name: "Generate key"
          openssh_keypair:
            path: /ansible/id_rsa
            force: True
        - name: "Add keys"
          command: #Overcomplicated {{ target }}
          with_target: "{{ groups['all'] }}"
    - name: Clean install docker #Strongly suspect that this fails because can't run commands as not root, and user doesn't privlage to root
      hosts: all
      tasks:
        - name: Fix filesystem #Consider reading up on docker prune in ansible docs https://docs.ansible.com/ansible/latest/modules/list_of_all_modules.html
          docker_prune:
            builder_cache: yes
            containers: yes
            images: yes
            volumes: yes
        - name: Purge /data/docker 
        - name: Purge /?/docker 
        - name: Build /data/docker directory 
          file:
            path: /data/docker 
            state: directory
            mode: '777'
        - name: Build /?/docker directory 
          file:
            path: /?/docker 
            state: directory
            mode: '777'
        - name: Create symbolic link 
          file: #I read the docker for src/dest but I don't like it
            src: /data/docker
            dest: /?/docker
            state: link
            mode: '777' #Can't prove this is right
        - name: I forgot what else this needs
        - name: Install docker
          yum: name=? #pick version, disable upgrade, 
    - name: Clean install helm, kubectl, rke on local 
      hosts: local
      tasks:
        - name: Build tmp directory 
          file:
            path: ./tmp 
            state: directory
            mode: '777'
        - name: Grab helm 
          get_url:
            url: #
            dest: ./tmp/"name" #Replace name with filename 
            mode: '777'
        - name: Unpack helm
        - name: Authorize helm 
        - name: Grab kubectl
          get_url:
            url: #
            dest: ./tmp/"name" #Replace name with filename 
            mode: '777'
        - name: Grab rke
          get_url:
            url: #
            dest: ./tmp/"name" #Replace name with filename 
            mode: '777'
        - name: Move helm to bin
        - name: Move kubectl to bin
        - name: Move rke to bin
    - name: Clean install helm, kubectl, rke on master #consider the user of copy https://docs.ansible.com/ansible/latest/modules/copy_module.html#copy-module
      hosts: master
      tasks:
        - name: Move files to master bin 
    - name: Clean tmp files
      hosts: local
      tasks:
        - name: Remove tmp files 
    - name: Create cluster
      hosts: local
      tasks:
        - name: Write the compose file
        - name: Create the rancher cluster
        - name: #Tiller?
        - name: #Certs?
        - name: #Rancher rollout 
      
      