---
- name: HA keyshare
  hosts: local 
  become: true
  become_user: root
  tasks:
  - name: Remove /home/$USER/.ssh #filepath is wrong.probs authorized keys
    file: 
      path: /home/$USER/.ssh
      state: absent
- name: Key passing to host
  hosts: master 
  become: true
  become_user: root
  serial: 1
  tasks:
  - name: Remove id_rsa
    file: 
      path: ./id_rsa
      state: absent
  - name: Remove id_rsa.pub
    file: 
      path: ./id_rsa.pub 
      state: absent
  - name: Generate key
    shell: #SSH key which has worked maybe shell
    #register: ssh_key #No way this works, need to take in file as var. If that also fails will need to copy file to local then move it in line by line 
    ssh_key: "{{ lookup('file', $path) }}"
  - name: Write to file
    local_action: 
      lineinfile:
        insertafter: EOF
        line: "{{ssh_key}}"
        path: /home/$USER/.ssh #No idea where ssh key is 
- name: Key pass to HA
  hosts: master
  become: true
  become_user: root
  tasks:
  - name: Remove old file
    file:
      path: #Unclear
      state: absent
  - name: Move the new file in 
    copy:
      src:  #Unclear
      dest: #Unclear
      remove_src: no #May be yes
      mode: '777'
    