---
#run as ansible-playbook -i hosts.ini machineChecker.yml --ask-become-pass --ask-pass -u $USER
- name: Write the local file
  hosts: local 
  become: true
  become_user: root
  tasks:
  - name: Remove machineData.txt
    file: 
      path: ./machineData.txt
      state: absent
  - name: Write machineData.txt
    file: 
      path: ./machineData.txt
      state: touch
      mode: '777'
  - name: Write firstline
    lineinfile: 
      line: [Address][DockerVersion][DockerGroup][StorageType]
      path: ./machineData.txt
- name: Collect vars
  hosts: all
  serial: 1
  become: true
  become_user: root
  tasks:
  - name: Collect version
    shell: docker --version
    register: Docker_Version #Consider calling cat on command
  - name: Collect group
    shell: cut -d: -f1 /etc/group | grep Docker 
    register: Docker_Group
  - name: Collect storage
    shell: docker info | grep -i Storage
    register: Storage_Type
  - name: Write to file
    local_action: 
      lineinfile:
        insertafter: EOF
        line: "[{{ inventory_hostname }}][{{ Docker_Version }}][{{ Docker_Group }}][{{ Storage_Type }}]" #Consider using std.out
        path: ./machineData.txt
